version: "3.8"

services:
  db:
    image: mysql:9.3
    container_name: ai-detection-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ai_detection_db
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - ai-network

  fastapi:
    build: ./ai-server
    container_name: ai-detection-fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./ai-server:/app
      - ./backend-spring/uploads:/app/uploads
    environment:
      - ENV=development
      - TZ=Asia/Seoul
    networks:
      - ai-network
    depends_on:
      - db

networks:
  ai-network:
    driver: bridge
