version: '3.8'

services:
  db:
    image: mysql:9.3
    container_name: ai-detection-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ai_detection_db
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge